# Generated by Django 5.2.7 on 2025-10-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, choices=[('general_medicine', 'General Medicine'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('orthopedics', 'Orthopedics'), ('gynecology_and_obstetrics', 'Gynecology & Obstetrics'), ('neurology', 'Neurology'), ('psychiatry_and_mental_health', 'Psychiatry & Mental Health')], max_length=50, null=True),
        ),
    ]
