# Generated by Django 5.2.7 on 2025-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialty',
            field=models.CharField(choices=[('general_medicine', 'General Medicine'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('orthopedics', 'Orthopedics'), ('gynecology_and_obstetrics', 'Gynecology & Obstetrics'), ('neurology', 'Neurology'), ('psychiatry_and_mental_health', 'Psychiatry & Mental Health')], max_length=100),
        ),
    ]
